import img from "../images/img1.jpeg";

import moment from "moment";

const tempData = [
  {
    date: moment().format("ll"),
    id: 3429432,
    room: 0,
    img: img,
    address: "2623 Honeysuckle Rd. NW",
    location: "atlanta, GA",
    lastOccupant: "Melissa Banks",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 830202,
    room: 0,
    img: img,
    address: "9870 colonial ave.",
    location: "decatur, GA",
    lastOccupant: "frankie vox",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 4498228,
    room: 0,
    img: img,
    address: "1822 riverside Dr. SW",
    location: "atlanta, GA",
    lastOccupant: "harry rutherford",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 4337299,
    room: 0,
    img: img,
    address: "990 Garden St.",
    location: "decatur, GA",
    lastOccupant: "clurke brast",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 1123854,
    room: 0,
    img: img,
    address: "3548 mongoose Rd. NE Apt 90",
    location: "buckhead, GA",
    lastOccupant: "erik van",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 9558833,
    room: 0,
    img: img,
    address: "7659 brookfield ave.",
    location: "morrow, GA",
    lastOccupant: "jerry tallah",
    uid: 89029,
    balance: 409.9,
  },
  {
    date: moment().format("ll"),
    id: 7338229,
    room: 0,
    img: img,
    address: "390 washington rd.",
    location: "atlanta, GA",
    lastOccupant: "olivia darks",
    uid: 89029,
    balance: 409.9,
  },
];

export default tempData;
